### ISSUE TITLE
Why use your own costmap_2d layer?

### ISSUE THREAD

**Issue by lericson** [rakeshshrestha31/ground_truth_layer#3]
Hi! What an interesting project, I had a similar idea as this and am now looking at your implementation. I will have several questions, and would be very happy to hear your thoughts on things.

First off, as the title states, I'm curious what the benefit is to using your own costmap updates? The obstacle layer of costmap_2d takes laser scanning data natively.

https://github.com/ros-planning/navigation/blob/melodic-devel/costmap_2d/plugins/obstacle_layer.cpp#L245

**Comment by lericson** [comment]
https://github.com/ros-perception/laser_geometry/blob/indigo-devel/src/laser_geometry.cpp

This is the projection used, it probably is a bit slower as it first creates a pointcloud though I doubt performance is limiting here?

**Comment by rakeshshrestha31** [comment]
Hi Ludvig. Thank you for your interest.

The reason we have our own costmap layer is application specific and for general purpose the obstacle layer is probably better. We needed a simple but efficient mapping with guaranteed updates on every new measurement.

We also wanted to get rid of bottlenecks from ROS due to TCP/IP communication. Meaning no topics, service, tf etc. So, we had to have our own costmap layer that we could directly use as a shared library from our main application and not as separate process (node) bypassing all the ROS interfacing (although it does provide addition topic interface which was not used in our application).

**Comment by lericson** [comment]
Aha I see, so it is not using these parts of ROS. I've found it a bit difficult to get the experiments to run, or even build inside of Catkin -- do you have any hints? If I put the base repository in `src`, the build fails to find hector_exploration_planner.

**Comment by rakeshshrestha31** [comment]
Is it just this package (ground_truth_layer) that you're trying to build or the [map_prediction_enhanced_exploration](https://github.com/rakeshshrestha31/map_prediction_enhanced_exploration)? This package does not have hector_exploration_planner as a dependency.

Can you post the complete error message? (Preferably on the issues section of the repo you're trying to build)

**Comment by lericson** [comment]
I've been trying to build the entire project, of course, but am not even sure where to begin -- in fact, where are the datasets used for training the model even saved? Like, where in the code, specifically? I cannot find any place saving JSON files, or any files called `boundingBox\d+.png`.

**Comment by rakeshshrestha31** [comment]
Sorry for the delay, and for the state of the repositories. I have updated the map_prediction_enhanced_exploration meta package along with README on how to build it. Make sure that you run "git submodule sync" if you're not cloning from scratch as some of the submodules have been updated.

I'm closing this issue. Please open a new issue on the map_prediction_enhanced_exploration repo to continue our discussion as it would be more appropriate there.
